// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbxbnrlnjahinwbmedhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNieGJucmxuamFoaW53Ym1lZGhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2Nzk4MDgsImV4cCI6MjA2NjI1NTgwOH0.VUFUOwXvaH_rY_aG2_xveZ7fgGS0Tys4SaE5-bpU3hw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);